name: Checkout 
on: [push]
jobs:
    checkout-action:
        runs-on: ubuntu-latest
        steps:
            - name: checkout with actions
              uses: actions/checkout@v3
    checkout-and-display-files:
        runs-on: ubuntu-latest
        steps:
            - name: List Files Before
              run: ls -a
            - name: Checkout
              run: | 
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout master
            - name: List Files After
              run: ls -a
