name: Commands
on: [push]
jobs:
    testing-wf-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Setting an error message
              run: echo "::error::Missing semicolon"
            - name: Setting an error message with parameteers
              run: echo "::error title=Error title,file=app.js, line=2, endLine=3,col=5,endColumn=7::Missing semicolon"
            - name: Setting a debug message with parameteers
              run: echo "::debug title=Debug title,file=app.js, line=2, endLine=3,col=5,endColumn=7::Missing semicolon"
            - name: Setting a warning message with parameteers
              run: echo "::warning title=Warning title,file=app.js, line=2, endLine=3,col=5,endColumn=7::Missing semicolon"
            - name: Setting a notice message with parameteers
              run: echo "::notice title=Notice title,file=app.js, line=2, endLine=3,col=5,endColumn=7::Missing semicolon"